### ISSUE TITLE
file input support request.

### ISSUE THREAD

**Issue by faststare** [milligram/milligram#160]
Please kindly support for file input save as and open file input. tia

**Comment by marcusasplund** [comment]
It is possible to achieve with something like this:

```html
    <label for="files" class="button file-label">Upload
    </label>
    <input
      onchange="yourUploadHandler(e)"
      accept=".csv, .doc, image/*"
      class="hidden"
      id="files"
      type="file" />
```
```css
.file-label {
  width: 15rem;
}
input[type=file].hidden {
  visibility: hidden;
  width: 15rem;
  margin-left: -15rem;
}
```
Heads up; do not wrap the label <em>around</em> the input, this will make IE (at least Edge) to go bonkers.
