### ISSUE TITLE
tested with normalize.css 7?

### ISSUE THREAD

**Issue by chuckreynolds** [milligram/milligram#167]
### Version info

**Milligram:** v1.3.0

**Other (e.g. normalize.css, node.js, npm, bower, browser, operating system) (if applicable):**
```
    "imagemin": "^5.2.2",
    "milligram": "^1.3.0",
    "node-sass": "^4.5.2",
    "normalize.css": "^7.0.0"
```

### Expected behavior

work with normalize.css v7.x

### Actual behavior

¯\_(ツ)_/¯

**Comment by cjpatoilo** [comment]
Hi @chuckreynolds 

I understand what you mean. However, you do not need to define the dependency normalize along with Milligram in your project. Only Milligram is enough. Normalize is implicitly defined in dependencies of Milligram so it will be installed in the same way.

Let me know what's new in the new version of Normalize

**Comment by chuckreynolds** [comment]
well, there's this: https://github.com/necolas/normalize.css/blob/master/CHANGELOG.md

**Comment by cjpatoilo** [comment]
@chuckreynoldsI had already seen the changelog. Apparently it's just these changes:

```css
/* Removed */
html {
  font-family: sans-serif;
}

a:active,
a:hover {
  outline-width: 0;
}

fieldset {
  border: 1px solid #c0c0c0;
  margin: 0 2px;
}

/* Updated */
fieldset {
  padding: 0.35em 0.75em 0.625em;
}
```

Note, you can better visualize the changes from one version to another in this way:

[Normalize: v5.0.0 -> v7.0.0](https://github.com/necolas/normalize.css/compare/5.0.0...7.0.0#diff-bb3dde41d97f19be8ab7b4780a915d5e)

So I have not yet had the opportunity to do something more specific such as the visual regression test that Milligram possesses. I wanted to hear from you. Did you notice anything unusual in Milligram when you upgraded Normalize to version 7?

**Comment by cjpatoilo** [comment]
@chuckreynolds I had already seen the changelog. Apparently it's just these changes:

```css
/* Removed */
html {
  font-family: sans-serif;
}

a:active,
a:hover {
  outline-width: 0;
}

fieldset {
  border: 1px solid #c0c0c0;
  margin: 0 2px;
}

/* Updated */
fieldset {
  padding: 0.35em 0.75em 0.625em;
}
```

Note, you can better visualize the changes from one version to another in this way:

[Normalize: v5.0.0 -> v7.0.0](https://github.com/necolas/normalize.css/compare/5.0.0...7.0.0#diff-bb3dde41d97f19be8ab7b4780a915d5e)

So I have not yet had the opportunity to do something more specific such as the visual regression test that Milligram possesses. I wanted to hear from you. Did you notice anything unusual in Milligram when you upgraded Normalize to version 7?
