### ISSUE TITLE
How to push other elements to the right using my sidebar?

### ISSUE THREAD

**Issue by fooksupachai** [milligram/milligram#177]
I want to create a simple side-navigation that takes up the entire screen's height. I am using <br>[Milligram](http://milligram.io/) for my base, and I want my side-nav to work with it. I have the following set up:<br><br>[Codepen demo](https://codepen.io/anon/pen/ZLJmzJ)<br>
As you can see, my sidebar is the following element<br>
```html
<div class="sidebar"></div>
```
with the following styles:
```css
div.sidebar { 
      position: absolute; width: 250px; 
      height: 100%;
      z-index: 99; 
      background-color: black;
 }
```
This sort of works, the sidebar appears above all else, but everything else does not get pushed to the side. And if the screen is small, the content clashes with the sidebar.<br>
How can I make it so the sidebar pushes everything else (including the navbar) to the right by 250px(its width)? I know this will make things unusable on smaller screens, but I will give the user a way to toggle it.
