### ISSUE TITLE
Easily change highlight color (#9b4dca)

### ISSUE THREAD

**Issue by mterron** [milligram/milligram#191]
Using CSS3 variables (custom properties) it is possible to override the highlight color in 1 line of CSS.

In milligram.css have something along the lines of:
```
:root {
  --highlight-color: #9b4dca;
}
```

and then replace every ```#9b4dca``` with ```var(--highlight-color)```.

Once this is done, replacing the highlight color is as easy as including a custom.css file with 
```
:root {
  --highlight-color: #abcabc;
}
```

**Comment by dkundel** [comment]
I came here for the same thing ^^ but since it is written in SASS and you might want to support old browsers I would recommend doing a more fallback proven example like this:
```css
:root {

}

button {
  background-color: $color-primary;
  background-color: var(--color-primary, $color-primary);
}
```

This way browsers who don't support CSS custom properties will still fallback to a working version.

Cheers,
Dominik
